# Generated by Django 3.0.2 on 2020-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='主机IP')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=12, verbose_name='登录密码')),
                ('rsa_key', models.TextField(verbose_name='秘钥')),
                ('env', models.CharField(blank=True, choices=[('dev', '开发'), ('test', '测试'), ('pre', '预生产'), ('prod', '生产')], max_length=10, null=True, verbose_name='所属环境')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='组件')),
                ('component_type', models.CharField(choices=[('service', '后端Service'), ('web', '前端Web'), ('other', '其他')], max_length=12, verbose_name='组件类型')),
                ('memo', models.TextField(verbose_name='备注')),
            ],
        ),
    ]
