# Generated by Django 3.0.2 on 2020-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='rsa_key',
            field=models.TextField(blank=True, null=True, verbose_name='秘钥'),
        ),
    ]
