# Generated by Django 2.2 on 2020-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200113_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('service', '后端Service'), ('other', '其他')], max_length=12, verbose_name='组件类型'),
        ),
    ]
