# Generated by Django 3.0.2 on 2020-01-09 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='监控结果')),
                ('send_tool', models.CharField(max_length=32, verbose_name='发送工具')),
                ('send_status', models.CharField(blank=True, choices=[('y', '发送成功'), ('n', '发送失败')], max_length=4, null=True, verbose_name='发送状态')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dingding', '钉钉'), ('email', '邮箱')], default='dingding', max_length=10, verbose_name='工具名称')),
                ('tool_url', models.TextField(verbose_name='工具地址')),
            ],
        ),
        migrations.AddField(
            model_name='monitortemplates',
            name='send_tools',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monitor.MonitorTools', verbose_name='发送工具'),
            preserve_default=False,
        ),
    ]
