# Generated by Django 3.0.2 on 2020-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200109_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortools',
            name='tool_name',
            field=models.CharField(choices=[('dingding', '钉钉'), ('email', '邮箱')], default='dingding', max_length=10, verbose_name='工具名称'),
        ),
        migrations.AlterField(
            model_name='monitortools',
            name='name',
            field=models.CharField(max_length=10, verbose_name='名称'),
        ),
    ]
