# Generated by Django 2.2 on 2020-01-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200109_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsassets',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='是否监控'),
        ),
    ]
