# Generated by Django 2.2 on 2020-01-10 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_componentsassets_is_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='env',
            field=models.CharField(default=datetime.datetime(2020, 1, 10, 11, 44, 9, 70662, tzinfo=utc), max_length=32, verbose_name='环境'),
            preserve_default=False,
        ),
    ]
