# Generated by Django 2.2 on 2020-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_remove_monitortask_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='recover_status',
            field=models.BooleanField(default=False, verbose_name='是否恢复'),
        ),
    ]
