# Generated by Django 2.2 on 2020-01-10 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20200110_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='components_assets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.ComponentsAssets'),
            preserve_default=False,
        ),
    ]
