# Generated by Django 2.2 on 2020-01-10 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_monitortask_components_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='uuid_lable',
            field=models.CharField(default=datetime.datetime(2020, 1, 10, 12, 50, 8, 815857, tzinfo=utc), max_length=200, verbose_name='标识'),
            preserve_default=False,
        ),
    ]
