# Generated by Django 2.2 on 2020-01-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_monitortask_uuid_lable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentsassets',
            options={'ordering': ['-c_time'], 'verbose_name': '组件事件', 'verbose_name_plural': '组件事件'},
        ),
        migrations.AlterModelOptions(
            name='monitortask',
            options={'ordering': ['-c_time'], 'verbose_name': '监控结果', 'verbose_name_plural': '监控结果'},
        ),
        migrations.AlterModelOptions(
            name='monitortemplates',
            options={'verbose_name': '监控模板', 'verbose_name_plural': '监控模板'},
        ),
        migrations.AlterModelOptions(
            name='monitortools',
            options={'verbose_name': '监控工具', 'verbose_name_plural': '监控工具'},
        ),
        migrations.AddField(
            model_name='monitortask',
            name='components_host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='告警主机'),
        ),
    ]
