# Generated by Django 2.2 on 2020-01-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20200113_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortask',
            name='uuid_lable',
        ),
    ]
