# Generated by Django 2.2 on 2020-01-13 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_remove_monitortask_uuid_lable'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='redis_key',
            field=models.CharField(default=datetime.datetime(2020, 1, 13, 10, 9, 22, 517369, tzinfo=utc), max_length=200, verbose_name='redis_key'),
            preserve_default=False,
        ),
    ]
