# Generated by Django 2.2 on 2020-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_monitortask_redis_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='env',
            field=models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('pre', '预生产'), ('prod', '生产')], max_length=12, verbose_name='环境'),
        ),
    ]
