# Generated by Django 2.2 on 2020-01-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20200117_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsassets',
            name='monitor_interface',
            field=models.TextField(blank=True, null=True, verbose_name='监控接口地址'),
        ),
    ]
